### ISSUE TITLE
Bug in velocity values?

### ISSUE THREAD

**Issue by memoakten** [memo/pr_kinect2_tracker#6]
- When I pause a recording in Kinect Studio (i.e. static skeleton), velocity values are still changing (even though position values aren't changing)
- Velocity values are massive. like 2.4, 3.7 etc. (should probably be more a few orders of magnitude smaller)

**Comment by devtronslab** [comment]
Values no longer change when Kinect stream is paused 
Commit "Issues resolve #1"

**Comment by devtronslab** [comment]
This seems to be related to poor tracking. As far as I can see from the debug info, whenever there's good tracking of all joints, all velocity values seem sensible. When the Kinect tracking is erroneous, the ( frame_(n+1) - frame_(n) ) / time formula doesn't work. 

I'm guessing this is why the MaxPatch uses confidence values for the tracking of each joint. The problem is, Kinect.h seemingly only gives access to the confidence values for the HandStates. So it seems like the MaxPatch calculates these values itself. Any chance you could either send me a copy of the patch, or look into it yourself?

I propose we simply weight the velocity values by the average confidence of the two points:
( frame_(n+1) - frame(n) ) \* ( confidence_(n+1) + confidence_(n) ) / (2*time)

**Comment by memoakten** [comment]
I'm not sure about using confidence in the velocity, because as confidence goes up and down the velocity will go up and down like crazy. better to calculate velocity as is, and then the app can decide whether or not to use the velocity. 

Look at these velocity values, they're huge! And the tracking was quite stable (I'm playing back a recording). Definitely something not right here. 
![capture](https://cloud.githubusercontent.com/assets/144230/11441825/b18efcbc-9507-11e5-8c3a-a77814436f5a.JPG)

**Comment by memoakten** [comment]
sorry my bad, previously I was calculating velocity per frame. so the values are off by a factor of about 30x. looks about right
